export type SoorahListProps = {
  id: number
  title: string
  ayahCount: number
  order: number
  arabic: string
  city: "Mecca" | "Medina"
  juz: number[]
  sajda?: number[]
}

export const SOORAH_LIST: Array<SoorahListProps> = [
  {
    id: 0,
    title: "",
    ayahCount: 0,
    order: 0,
    arabic: "",
    city: "Mecca",
    juz: [],
  },
  {
    id: 1,
    title: "El-Fatiha",
    ayahCount: 7,
    order: 5,
    arabic: "الفاتحة",
    city: "Mecca",
    juz: [1],
  },
  {
    id: 2,
    title: "El-Bekara",
    ayahCount: 286,
    order: 87,
    arabic: "البقرة",
    city: "Medina",
    juz: [1, 2, 3],
  },
  {
    id: 3,
    title: "Ali Imran",
    ayahCount: 200,
    order: 89,
    arabic: "آل عمران",
    city: "Medina",
    juz: [4, 5],
  },
  {
    id: 4,
    title: "En-Nisa",
    ayahCount: 176,
    order: 92,
    arabic: "النساء",
    city: "Medina",
    juz: [5, 6],
  },
  {
    id: 5,
    title: "El-Ma'ide",
    ayahCount: 120,
    order: 112,
    arabic: "المائدة",
    city: "Medina",
    juz: [6, 7],
  },
  {
    id: 6,
    title: "El-En'am",
    ayahCount: 165,
    order: 55,
    arabic: "الأنعام",
    city: "Mecca",
    juz: [7, 8],
  },
  {
    id: 7,
    title: "El-A'raf",
    ayahCount: 206,
    order: 39,
    arabic: "الأعراف",
    city: "Mecca",
    juz: [8, 9],
    sajda: [206],
  },
  {
    id: 8,
    title: "El-Enfal",
    ayahCount: 75,
    order: 88,
    arabic: "الأنفال",
    city: "Medina",
    juz: [9, 10],
  },
  {
    id: 9,
    title: "Et-Tevba",
    ayahCount: 129,
    order: 113,
    arabic: "التوبة",
    city: "Medina",
    juz: [10, 11],
  },
  {
    id: 10,
    title: "Junus",
    ayahCount: 109,
    order: 51,
    arabic: "يونس",
    city: "Mecca",
    juz: [11],
  },
  {
    id: 11,
    title: "Hud",
    ayahCount: 123,
    order: 52,
    arabic: "هود",
    city: "Mecca",
    juz: [11, 12],
  },
  {
    id: 12,
    title: "Jusuf",
    ayahCount: 111,
    order: 53,
    arabic: "يوسف",
    city: "Mecca",
    juz: [12, 13],
  },
  {
    id: 13,
    title: "Er-Ra'd",
    ayahCount: 43,
    order: 96,
    arabic: "الرعد",
    city: "Medina",
    juz: [13],
    sajda: [15],
  },
  {
    id: 14,
    title: "Ibrahim",
    ayahCount: 52,
    order: 72,
    arabic: "ابراهيم",
    city: "Mecca",
    juz: [13],
  },
  {
    id: 15,
    title: "El-Hidžr",
    ayahCount: 99,
    order: 54,
    arabic: "الحجر",
    city: "Mecca",
    juz: [14],
  },
  {
    id: 16,
    title: "En-Nahl",
    ayahCount: 128,
    order: 70,
    arabic: "النحل",
    city: "Mecca",
    juz: [14],
    sajda: [50],
  },
  {
    id: 17,
    title: "El-Isra",
    ayahCount: 111,
    order: 50,
    arabic: "الإسراء",
    city: "Mecca",
    juz: [15],
    sajda: [109],
  },
  {
    id: 18,
    title: "El-Kehf",
    ayahCount: 110,
    order: 69,
    arabic: "الكهف",
    city: "Mecca",
    juz: [15, 16],
  },
  {
    id: 19,
    title: "Merjem",
    ayahCount: 98,
    order: 44,
    arabic: "مريم",
    city: "Mecca",
    juz: [16],
    sajda: [22],
  },
  {
    id: 20,
    title: "Ta-Ha",
    ayahCount: 135,
    order: 45,
    arabic: "طه",
    city: "Mecca",
    juz: [16],
  },
  {
    id: 21,
    title: "El-Enbija",
    ayahCount: 112,
    order: 73,
    arabic: "الأنبياء",
    city: "Mecca",
    juz: [17],
  },
  {
    id: 22,
    title: "El-Hadždž",
    ayahCount: 78,
    order: 103,
    arabic: "الحج",
    city: "Medina",
    juz: [17],
    sajda: [18, 77],
  },
  {
    id: 23,
    title: "El-Mu'minun",
    ayahCount: 118,
    order: 74,
    arabic: "المؤمنون",
    city: "Mecca",
    juz: [18],
  },
  {
    id: 24,
    title: "En-Nur",
    ayahCount: 64,
    order: 102,
    arabic: "النور",
    city: "Medina",
    juz: [18],
  },
  {
    id: 25,
    title: "El-Furkan",
    ayahCount: 77,
    order: 42,
    arabic: "الفرقان",
    city: "Mecca",
    juz: [18, 19],
    sajda: [60],
  },
  {
    id: 26,
    title: "Eš-Šu'ara",
    ayahCount: 227,
    order: 47,
    arabic: "الشعراء",
    city: "Mecca",
    juz: [19],
  },
  {
    id: 27,
    title: "En-Neml",
    ayahCount: 93,
    order: 48,
    arabic: "النمل",
    city: "Mecca",
    juz: [19, 20],
    sajda: [26],
  },
  {
    id: 28,
    title: "El-Kasas",
    ayahCount: 88,
    order: 49,
    arabic: "القصص",
    city: "Mecca",
    juz: [20],
  },
  {
    id: 29,
    title: "El-'Ankebut",
    ayahCount: 69,
    order: 85,
    arabic: "العنكبوت",
    city: "Mecca",
    juz: [20, 21],
  },
  {
    id: 30,
    title: "Er-Rum",
    ayahCount: 60,
    order: 84,
    arabic: "الروم",
    city: "Mecca",
    juz: [21],
  },
  {
    id: 31,
    title: "Lukman",
    ayahCount: 34,
    order: 57,
    arabic: "لقمان",
    city: "Mecca",
    juz: [21],
  },
  {
    id: 32,
    title: "Es-Sedžda",
    ayahCount: 30,
    order: 75,
    arabic: "السجدة",
    city: "Mecca",
    juz: [21],
    sajda: [15],
  },
  {
    id: 33,
    title: "El-Ahzab",
    ayahCount: 73,
    order: 90,
    arabic: "الأحزاب",
    city: "Medina",
    juz: [21, 22],
  },
  {
    id: 34,
    title: "Saba",
    ayahCount: 54,
    order: 58,
    arabic: "سبإ",
    city: "Mecca",
    juz: [22],
  },
  {
    id: 35,
    title: "Fatir",
    ayahCount: 45,
    order: 43,
    arabic: "فاطر",
    city: "Mecca",
    juz: [22],
  },
  {
    id: 36,
    title: "Ja-sin",
    ayahCount: 83,
    order: 41,
    arabic: "يس",
    city: "Mecca",
    juz: [22, 23],
  },
  {
    id: 37,
    title: "Es-Saffat",
    ayahCount: 182,
    order: 56,
    arabic: "الصافات",
    city: "Mecca",
    juz: [23],
  },
  {
    id: 38,
    title: "Sād",
    ayahCount: 88,
    order: 38,
    arabic: "ص",
    city: "Mecca",
    juz: [23],
    sajda: [24],
  },
  {
    id: 39,
    title: "Ez-Zumer",
    ayahCount: 75,
    order: 59,
    arabic: "الزمر",
    city: "Mecca",
    juz: [23, 24],
  },
  {
    id: 40,
    title: "Gafir",
    ayahCount: 85,
    order: 60,
    arabic: "غافر",
    city: "Mecca",
    juz: [24, 25],
  },
  {
    id: 41,
    title: "Fusilet",
    ayahCount: 54,
    order: 61,
    arabic: "فصلت",
    city: "Mecca",
    juz: [24, 25],
    sajda: [38],
  },
  {
    id: 42,
    title: "Eš-Šura",
    ayahCount: 53,
    order: 62,
    arabic: "الشورى",
    city: "Mecca",
    juz: [25],
  },
  {
    id: 43,
    title: "Ez-Zuhruf",
    ayahCount: 89,
    order: 63,
    arabic: "الزخرف",
    city: "Mecca",
    juz: [25],
  },
  {
    id: 44,
    title: "Ed-Duhan",
    ayahCount: 59,
    order: 64,
    arabic: "الدخان",
    city: "Mecca",
    juz: [25],
  },
  {
    id: 45,
    title: "El-Gašije",
    ayahCount: 37,
    order: 65,
    arabic: "الجاثية",
    city: "Mecca",
    juz: [25],
  },
  {
    id: 46,
    title: "El-Ahkaf",
    ayahCount: 35,
    order: 66,
    arabic: "الأحقاف",
    city: "Mecca",
    juz: [26],
  },
  {
    id: 47,
    title: "Muhammed",
    ayahCount: 38,
    order: 95,
    arabic: "محمد",
    city: "Medina",
    juz: [26],
  },
  {
    id: 48,
    title: "El-Feth",
    ayahCount: 29,
    order: 111,
    arabic: "الفتح",
    city: "Medina",
    juz: [26],
  },
  {
    id: 49,
    title: "El-Hudžurat",
    ayahCount: 18,
    order: 106,
    arabic: "الحجرات",
    city: "Medina",
    juz: [26],
  },
  {
    id: 50,
    title: "Kāf",
    ayahCount: 45,
    order: 34,
    arabic: "ق",
    city: "Mecca",
    juz: [26],
  },
  {
    id: 51,
    title: "Ez-Zarijat",
    ayahCount: 60,
    order: 67,
    arabic: "الذاريات",
    city: "Mecca",
    juz: [26, 27],
  },
  {
    id: 52,
    title: "Et-Tur",
    ayahCount: 49,
    order: 76,
    arabic: "الطور",
    city: "Mecca",
    juz: [27],
  },
  {
    id: 53,
    title: "En-Nedžm",
    ayahCount: 62,
    order: 23,
    arabic: "النجم",
    city: "Mecca",
    juz: [27],
    sajda: [62],
  },
  {
    id: 54,
    title: "El-Kamer",
    ayahCount: 55,
    order: 37,
    arabic: "القمر",
    city: "Mecca",
    juz: [27],
  },
  {
    id: 55,
    title: "Er-Rahman",
    ayahCount: 78,
    order: 97,
    arabic: "الرحمن",
    city: "Medina",
    juz: [27],
  },
  {
    id: 56,
    title: "El-Vaki'a",
    ayahCount: 96,
    order: 46,
    arabic: "الواقعة",
    city: "Mecca",
    juz: [27],
  },
  {
    id: 57,
    title: "El-Hadid",
    ayahCount: 29,
    order: 94,
    arabic: "الحديد",
    city: "Medina",
    juz: [27],
  },
  {
    id: 58,
    title: "El-Mudžadela",
    ayahCount: 22,
    order: 105,
    arabic: "المجادلة",
    city: "Medina",
    juz: [28],
  },
  {
    id: 59,
    title: "El-Hašr",
    ayahCount: 24,
    order: 101,
    arabic: "الحشر",
    city: "Medina",
    juz: [28],
  },
  {
    id: 60,
    title: "El-Mumtehine",
    ayahCount: 13,
    order: 91,
    arabic: "الممتحنة",
    city: "Medina",
    juz: [28],
  },
  {
    id: 61,
    title: "Es-Saff",
    ayahCount: 14,
    order: 109,
    arabic: "الصف",
    city: "Medina",
    juz: [28],
  },
  {
    id: 62,
    title: "El-Džumu'a",
    ayahCount: 11,
    order: 110,
    arabic: "الجمعة",
    city: "Medina",
    juz: [28],
  },
  {
    id: 63,
    title: "El-Munafikun",
    ayahCount: 11,
    order: 104,
    arabic: "المنافقون",
    city: "Medina",
    juz: [28],
  },
  {
    id: 64,
    title: "Et-Tegabun",
    ayahCount: 18,
    order: 108,
    arabic: "التغابن",
    city: "Medina",
    juz: [28],
  },
  {
    id: 65,
    title: "Et-Talak",
    ayahCount: 12,
    order: 99,
    arabic: "الطلاق",
    city: "Medina",
    juz: [28],
  },
  {
    id: 66,
    title: "Et-Tahrim",
    ayahCount: 12,
    order: 107,
    arabic: "التحريم",
    city: "Medina",
    juz: [28],
  },
  {
    id: 67,
    title: "El-Mulk",
    ayahCount: 30,
    order: 77,
    arabic: "الملك",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 68,
    title: "El-Kalem",
    ayahCount: 52,
    order: 2,
    arabic: "القلم",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 69,
    title: "El-Hakka",
    ayahCount: 52,
    order: 78,
    arabic: "الحاقة",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 70,
    title: "El-Me'aridž",
    ayahCount: 44,
    order: 79,
    arabic: "المعارج",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 71,
    title: "Nuh",
    ayahCount: 28,
    order: 71,
    arabic: "نوح",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 72,
    title: "El-Džinn",
    ayahCount: 28,
    order: 40,
    arabic: "الجن",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 73,
    title: "El-Muzzemmil",
    ayahCount: 20,
    order: 3,
    arabic: "المزمل",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 74,
    title: "El-Muddessir",
    ayahCount: 56,
    order: 4,
    arabic: "المدثر",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 75,
    title: "El-Kijame",
    ayahCount: 40,
    order: 31,
    arabic: "القيامة",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 76,
    title: "El-Insan",
    ayahCount: 31,
    order: 98,
    arabic: "الانسان",
    city: "Medina",
    juz: [29],
  },
  {
    id: 77,
    title: "El-Murselat",
    ayahCount: 50,
    order: 33,
    arabic: "المرسلات",
    city: "Mecca",
    juz: [29],
  },
  {
    id: 78,
    title: "En-Nebe'",
    ayahCount: 40,
    order: 80,
    arabic: "النبإ",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 79,
    title: "En-Nazi'at",
    ayahCount: 46,
    order: 81,
    arabic: "النازعات",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 80,
    title: "'Abese",
    ayahCount: 42,
    order: 24,
    arabic: "عبس",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 81,
    title: "Et-Takvir",
    ayahCount: 29,
    order: 7,
    arabic: "التكوير",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 82,
    title: "El-Infitar",
    ayahCount: 19,
    order: 82,
    arabic: "الإنفطار",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 83,
    title: "El-Mutaffifin",
    ayahCount: 36,
    order: 86,
    arabic: "المطففين",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 84,
    title: "El-Inšikak",
    ayahCount: 25,
    order: 83,
    arabic: "الإنشقاق",
    city: "Mecca",
    juz: [30],
    sajda: [21],
  },
  {
    id: 85,
    title: "El-Burudž",
    ayahCount: 22,
    order: 27,
    arabic: "البروج",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 86,
    title: "Et-Tarik",
    ayahCount: 17,
    order: 36,
    arabic: "الطارق",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 87,
    title: "El-'Ala",
    ayahCount: 19,
    order: 8,
    arabic: "الأعلى",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 88,
    title: "El-Gašije",
    ayahCount: 26,
    order: 68,
    arabic: "الغاشية",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 89,
    title: "El-Fedžr",
    ayahCount: 30,
    order: 10,
    arabic: "الفجر",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 90,
    title: "El-Beled",
    ayahCount: 20,
    order: 35,
    arabic: "البلد",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 91,
    title: "Eš-Šems",
    ayahCount: 15,
    order: 26,
    arabic: "الشمس",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 92,
    title: "El-Lejl",
    ayahCount: 21,
    order: 9,
    arabic: "الليل",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 93,
    title: "Ed-Duha",
    ayahCount: 11,
    order: 11,
    arabic: "الضحى",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 94,
    title: "El-Inširah",
    ayahCount: 8,
    order: 12,
    arabic: "الشرح",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 95,
    title: "Et-Tin",
    ayahCount: 8,
    order: 28,
    arabic: "التين",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 96,
    title: "El-'Alek",
    ayahCount: 19,
    order: 1,
    arabic: "العلق",
    city: "Mecca",
    juz: [30],
    sajda: [19],
  },
  {
    id: 97,
    title: "El-Kadr",
    ayahCount: 5,
    order: 25,
    arabic: "القدر",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 98,
    title: "El-Bejjine",
    ayahCount: 8,
    order: 100,
    arabic: "البينة",
    city: "Medina",
    juz: [30],
  },
  {
    id: 99,
    title: "Ez-Zilzal",
    ayahCount: 8,
    order: 93,
    arabic: "الزلزلة",
    city: "Medina",
    juz: [30],
  },
  {
    id: 100,
    title: "El-'Adijat",
    ayahCount: 11,
    order: 14,
    arabic: "العاديات",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 101,
    title: "El-Kari'a",
    ayahCount: 11,
    order: 30,
    arabic: "القارعة",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 102,
    title: "Et-Tekasur",
    ayahCount: 8,
    order: 16,
    arabic: "التكاثر",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 103,
    title: "El-'Asr",
    ayahCount: 3,
    order: 13,
    arabic: "العصر",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 104,
    title: "El-Humeze",
    ayahCount: 9,
    order: 32,
    arabic: "الهمزة",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 105,
    title: "El-Fil",
    ayahCount: 5,
    order: 19,
    arabic: "الفيل",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 106,
    title: "Kurejš",
    ayahCount: 4,
    order: 29,
    arabic: "قريش",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 107,
    title: "El-Ma'un",
    ayahCount: 7,
    order: 17,
    arabic: "الماعون",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 108,
    title: "El-Kevser",
    ayahCount: 3,
    order: 15,
    arabic: "الكوثر",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 109,
    title: "El-Kafirun",
    ayahCount: 6,
    order: 18,
    arabic: "الكافرون",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 110,
    title: "En-Nasr",
    ayahCount: 3,
    order: 114,
    arabic: "النصر",
    city: "Medina",
    juz: [30],
  },
  {
    id: 111,
    title: "El-Leheb",
    ayahCount: 5,
    order: 6,
    arabic: "المسد",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 112,
    title: "El-Ihlas",
    ayahCount: 4,
    order: 22,
    arabic: "الإخلاص",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 113,
    title: "El-Felek",
    ayahCount: 5,
    order: 20,
    arabic: "الفلق",
    city: "Mecca",
    juz: [30],
  },
  {
    id: 114,
    title: "En-Nas",
    ayahCount: 6,
    order: 21,
    arabic: "الناس",
    city: "Mecca",
    juz: [30],
  },
] as const

export const soorahList = SOORAH_LIST.slice(1)